### ISSUE TITLE
[feature request] caching tiles on disk

### ISSUE THREAD

**Issue by darvin** [melowntech/vts-browser-unity-plugin#11]
is it supported?

**Comment by malytomas** [comment]
Yes, VTS does that automatically.

See https://github.com/melowntech/vts-browser-unity-plugin/blob/master/src/Vts/Documentation/readme.md#vts-cache

**Comment by darvin** [comment]
@malytomas thank you!

in demo scenes on Mac it loads every asset every time tho - is it because of running in Unity editor? Is that expected?

**Comment by malytomas** [comment]
I assume that by _loads_ you mean _downloads_ eg. from internet?
Running in the editor should have no effect on this.
It will always download few files in the beginning: mapconfig, authentication config, bound layer configs etc. Meshes and textures should be correctly cached.
I suggest to increase logging level in file:
https://github.com/melowntech/vts-browser-unity-plugin/blob/ae7d4ef11f95f395c7e11a889570ba7f209e8408/src/Vts/Scripts/BrowserUtil/VtsLog.cs#L53
see if that helps?
