### ISSUE TITLE
build for iOS return errors

### ISSUE THREAD

**Issue by kenazossou** [melowntech/vts-browser-unity-plugin#12]
I'm trying to build for iOS using an "iPad air 2" with 13.1 iPadOS version.
The broadcast works well (Using Unity Remote 5) and the xCode project building successed too(According to instructions here : https://github.com/melowntech/vts-browser-unity-plugin).

![image](https://user-images.githubusercontent.com/24231547/71663996-8ed5c380-2d57-11ea-93b4-fb131e8fba29.png)

But when I tried to build iPad app from xCode, I encounter this error :
ReleaseForRunning-iphoneos/Child.app/Child normal arm64 (in target 'Unity-iPhone' from project 'Unity-iPhone')
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-ios9.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk -L/Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Products/ReleaseForRunning-iphoneos -L/Users/cefa/Desktop/iOS_12-27-2019_2-40-PM -L/Users/cefa/Desktop/iOS_12-27-2019_2-40-PM/Libraries -F/Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Products/ReleaseForRunning-iphoneos -F/Users/cefa/Desktop/iOS_12-27-2019_2-40-PM/Frameworks/Vts/Plugins/ios64 -filelist /Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/Child.LinkFileList -Xlinker -map -Xlinker /Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Child-LinkMap-normal-arm64.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/Child_lto.o -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -framework Security -framework MediaToolbox -liPhone-lib -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -framework vts-browser -weak_framework Metal -Xlinker -dependency_info -Xlinker /Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/Unity-iPhone.build/Objects-normal/arm64/Child_dependency_info.dat -o /Users/cefa/Library/Developer/Xcode/DerivedData/Unity-iPhone-etathkjjatedvcanhmrbctxohpxk/Build/Products/ReleaseForRunning-iphoneos/Child.app/Child

Undefined symbols for architecture arm64:
  "_vtsInternalMemoryRead", referenced from:
      _BrowserInterop_vtsInternalMemoryRead_mD62A3E07823C4C3103E426982D99F34B107CA133 in Assembly-CSharp1.o
     (maybe you meant: _BrowserInterop_vtsInternalMemoryRead_mD62A3E07823C4C3103E426982D99F34B107CA133)
  "_vtsInternalMemoryExists", referenced from:
      _BrowserInterop_vtsInternalMemoryExists_mAB72D6C5EAF481086765E65FFDA50D564FA00BC4 in Assembly-CSharp1.o
     (maybe you meant: _BrowserInterop_vtsInternalMemoryExists_mAB72D6C5EAF481086765E65FFDA50D564FA00BC4)
  "_vtsCallbacksProjFinder", referenced from:
      _BrowserInterop_vtsCallbacksProjFinder_m053FA97CBF15A9F70EB9238C0A6F35ADC89B6DCE in Assembly-CSharp1.o
     (maybe you meant: _BrowserInterop_vtsCallbacksProjFinder_m053FA97CBF15A9F70EB9238C0A6F35ADC89B6DCE)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Showing Recent Issues
Undefined symbol: _vtsInternalMemoryRead

Could anyone help, please

**Comment by malytomas** [comment]
Thanks for the report.
It is fixed in the master branch now. It will be included in next asset store release too.
In the meantime, It is possible to just comment these functions in interop.cs. They are not needed.
