### ISSUE TITLE
I have problems loading a 3d map

### ISSUE THREAD

**Issue by HeFake** [melowntech/vts-browser-unity-plugin#13]
I have problems loading a 3d map.  I downloaded this resource from the asset store to two computers, and this problem is everywhere.  There are no errors in the console.

Picture - https://drive.google.com/file/d/1N5pUDIrPjAyoIKF5GTjfszekioHlwPjM/view?usp=drivesdk

**Comment by malytomas** [comment]
This looks good. The default mapconfig does not provide detailed data outside that city center. You should use different mapconfig or configure your own vts backand with your own data.

**Comment by HeFake** [comment]
Forgive me for my stupid questions, but is it possible to use Google Earth ?

**Comment by malytomas** [comment]
Google has its own integration with Unity 3D:
https://cloud.google.com/maps-platform/gaming/
It is not compatible with vts.

**Comment by HeFake** [comment]
Thank you
