### ISSUE TITLE
Place custom 3dmax model

### ISSUE THREAD

**Issue by fingerx** [melowntech/vts-browser-unity-plugin#15]
I tried to find the documentation but did not find the information I needed. If it is a real building, it can be obtained by scanning. But if I have a part of the data for the planned building, I build the model through 3dmax. How exactly can these models be placed in the designated area. thank.

**Comment by malytomas** [comment]
You can use this function:
https://github.com/melowntech/vts-browser-unity-plugin/blob/ee67b39bd6f4fbf5f9379d40f7582629b72f0304/src/Vts/Scripts/VtsMap.cs#L102
to get the coordinates for the origin of the building from lat,lon,alt.
However, it may require some more tweaks to get correct orientation.
I have been asked this question multiple times so I will add an example in the plugin.

**Comment by fingerx** [comment]
@malytomas  thanks

**Comment by malytomas** [comment]
I have added the example application. It will take some more time before I upload it to unity store, but you can use it from github.

**Comment by fingerx** [comment]
@malytomas  thanks
