### ISSUE TITLE
Import VTS Landscape Streaming Plugin in unity and can't work

### ISSUE THREAD

**Issue by chiachiliou** [melowntech/vts-browser-unity-plugin#18]
I download VTS Landscape Streaming Plugin package in unity.
When I open every scene in Vts/Demo,and press play ,it always pop up error messages.
I've Followed the command to set up the link, but still can’t run.

![VTS_ErrorMessage](https://user-images.githubusercontent.com/35550039/92362596-c97fcf00-f122-11ea-9864-a1f0650da010.JPG)

**Comment by malytomas** [comment]
Hi,
Did you download it from unity store or from github?
