### ISSUE TITLE
the plugin in Unity  Cant run   Error downloading <https://cdn.melown.com/vts/melown2015/unity/world/mapConfig.json>

### ISSUE THREAD

**Issue by zhuxian1guo** [melowntech/vts-browser-unity-plugin#20]
![image](https://user-images.githubusercontent.com/34300047/95704016-23276c00-0c82-11eb-9a9d-0424b471c6cc.png)
![image](https://user-images.githubusercontent.com/34300047/95704030-2cb0d400-0c82-11eb-8596-971fb71b7613.png)

Error downloading <https://cdn.melown.com/vts/melown2015/unity/world/mapConfig.json>, http code 10500 {resources.cpp:vts::FetchTaskImpl::fetchDone():110}
UnityEngine.Debug:Log(Object)
VtsLog:LogCallback(String) (at Assets/Vts/Scripts/BrowserUtil/VtsLog.cs:46)

**Comment by malytomas** [comment]
Can you test access the url from regular web browser?

**Comment by zhuxian1guo** [comment]
> 您可以测试从常规Web浏览器访问URL吗？

https://cdn.melown.com/mario/store/melown2015/map-config/melown/Melown-Earth-Intergeo-2017/mapConfig.json  
This  url  can access

**Comment by malytomas** [comment]
Good. Can you also access the https://cdn.melown.com/vts/melown2015/unity/world/mapConfig.json in firefox or chrome?

**Comment by zhuxian1guo** [comment]
> Good. Can you also access the https://cdn.melown.com/vts/melown2015/unity/world/mapConfig.json in firefox or chrome?

YES

**Comment by zhuxian1guo** [comment]
> Good. Can you also access the https://cdn.melown.com/vts/melown2015/unity/world/mapConfig.json in firefox or chrome?
![image](https://user-images.githubusercontent.com/34300047/95723268-8972b580-0ca7-11eb-8251-4436b9f7a3eb.png)
![image](https://user-images.githubusercontent.com/34300047/95723287-90012d00-0ca7-11eb-96ce-72adfe26d224.png)

**Comment by malytomas** [comment]
Thanks for the image of the logs.
It shows error code 35, ssl error.
Can you, temporarily, change the url to http instead of https?

**Comment by zhuxian1guo** [comment]
> https

3Q  Very Much !

**Comment by zhuxian1guo** [comment]
> Thanks for the image of the logs.
> It shows error code 35, ssl error.
> Can you, temporarily, change the url to http instead of https?

thank u very much!!

**Comment by malytomas** [comment]
It would be best to figure out why the ssl does not work and fix it.
Using http (without ssl) should only be considered as a temporary workaround.
Can you try to access the url with curl from command line to see if that has the same issue?

**Comment by zhuxian1guo** [comment]
> It would be best to figure out why the ssl does not work and fix it.
> Using http (without ssl) should only be considered as a temporary workaround.
> Can you try to access the url with curl from command line to see if that has the same issue?
I Download  Curl and Test-->  
![image](https://user-images.githubusercontent.com/34300047/95805136-452ef600-0d37-11eb-9e0e-dbf5cf369786.png)

**Comment by malytomas** [comment]
Thanks for the test.
The certificate should be restored now - it was an issue on our cdn.
Please, try it again and let me know.

**Comment by zhuxian1guo** [comment]
> Thanks for the test.
> The certificate should be restored now - it was an issue on our cdn.
> Please, try it again and let me know.

Play normal 
![Uploading image.png…]()

**Comment by malytomas** [comment]
Thanks for the report.
