### ISSUE TITLE
Run in editor mode

### ISSUE THREAD

**Issue by FilipeJorgeTekuchi** [melowntech/vts-browser-unity-plugin#21]
Hey,

Hacking in the source code to make vts stream in editor mode when not playing, but struggling to make it work!

Any tip on how to do it?

Thanks!

**Comment by malytomas** [comment]
Hi, I never tried it.
What exactly is it that you are struggling with?
Furthermore, if someone uses a reference to object (map chunk) generated in editor mode, that reference becomes invalid in play mode, which might be more confusing than how it is now.

**Comment by FilipeJorgeTekuchi** [comment]
Hey, added some [ExecuteInEditMode] to some scripts, and as expected I'm getting errors, and been trying to fix some but I'm doing this in the brute force way, without really understanding how stuff works inside. Almost sure there is a smarter way to do this, I'm going to keep trying, but if you have any tip or guideline how to make it work, let me know.

Thanks!
