### ISSUE TITLE
Changing mapconfig path to < http://192.168.110.22:8070/store/map-config/cadastre/mapConfig.json>, without authentication {map.cpp:vts::MapImpl::setMapconfigPath():172}

### ISSUE THREAD

**Issue by veyvin** [melowntech/vts-browser-unity-plugin#22]
![image](https://user-images.githubusercontent.com/6776758/96663365-2063ff80-1383-11eb-8c0c-9105ab868342.png)
![image](https://user-images.githubusercontent.com/6776758/96663429-3e316480-1383-11eb-9aae-cee6d7dfdedb.png)

**Comment by malytomas** [comment]
There is space in front of the http.
