### ISSUE TITLE
LOD Load distance and culling

### ISSUE THREAD

**Issue by Tekn1ck** [melowntech/vts-browser-unity-plugin#23]
Two questions:

What would be the best way to force an LOD load distance? Lets say I want to load the highest LOD for a distance of 500m from the camera for example. Or once loaded never unload the lowest LOD, what is the best approach?

The camera occlusion works well - but I notice that it still loads tiles when they are hidden behind objects. Is there a way to use occlusion culling?

**Comment by malytomas** [comment]
Hi @Tekn1ck,

> What would be the best way to force an LOD load distance? Lets say I want to load the highest LOD for a distance of 500m from the camera for example. Or once loaded never unload the lowest LOD, what is the best approach?

https://github.com/melowntech/vts-browser-cpp/blob/d1ac85bc1d913fa5651d1787ad61b1b18c4a611e/browser/src/vts-libbrowser/include/vts-browser/cameraOptions.hpp#L48 this option is bias for LOD selection. Using smaller value will force loading finer details.
The options in Unity are JSON encoded, but the names are the same.

Furthermore, you may experiment with various loading modes. Eg. the fixed traversal mode lets you choose one particular LOD and a distance. However, nothing will be loaded further than the selected distance in this mode.

> The camera occlusion works well - but I notice that it still loads tiles when they are hidden behind objects. Is there a way to use occlusion culling?

At the moment, VTS does not support any occlusion culling. We are considering adding it in some form, however, it is rather difficult. Either, it could be computed on cpu, which would require some simplified occlusion masks, or using occlusion queries in gpu, which would make it difficult to keep the native library rendering api agnostic.
