### ISSUE TITLE
Running a build on another computer

### ISSUE THREAD

**Issue by Tekn1ck** [melowntech/vts-browser-unity-plugin#24]
Can you tell me if there is a reason why the map would not load on some computers and not others?

We have found this in the unity log

![image](https://user-images.githubusercontent.com/67991497/99627649-cd1bc480-2a88-11eb-83cc-f34871bba18d.png)

EDIT: We found the build would work after we installed Unity on a new computer where we tried to run the build. What dependencies does a build need in order to run on a computer without Unity installed?

**Comment by malytomas** [comment]
Hi,

Please try installing visual studio c++ redistributable for vs 2019:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Let me know if that solves the problem.

**Comment by Tekn1ck** [comment]
will have a go - thanks

**Comment by Tekn1ck** [comment]
Can confirm that this works
