### ISSUE TITLE
How does VTS support photogrammetric 3D models such as I3S?

### ISSUE THREAD

**Issue by Davionshi** [melowntech/vts-browser-unity-plugin#25]
I have set up a VTS backend, but I don't find any guide about how to support I3S file. Can anyone provide an explain about it? Thanks.

**Comment by malytomas** [comment]
Please take a look at: https://github.com/melowntech/workshop/issues/27#issuecomment-655364992
I3S should be possible to convert to slpk (or try to load it directly?).
If you have any further question on this topic, please ask them at https://github.com/melowntech/vts-tools
