### ISSUE TITLE
use tiled images download from bingmap

### ISSUE THREAD

**Issue by huosk** [melowntech/vts-browser-unity-plugin#26]
Hello,

I have some tiled images download from bingmap, how can I use them? I have read the tutorial in detail, but still haven't found the way.

Thanks

**Comment by malytomas** [comment]
Tiled imagery is used in VTS as bound layer.
Here is a tutorial: https://vts-geospatial.org/tutorials/bing-maps.html?highlight=bound

Feel free to ask if you have any further questions - be as specific as possible.
