### ISSUE TITLE
How can I change the Cache path in Unity VTS plugin?

### ISSUE THREAD

**Issue by rafaP** [melowntech/vts-browser-unity-plugin#27]
Hi Melowntech,
I want to change the cache path in Windows app made with Unity.

Acourding your documentation is possible,
https://github.com/melowntech/vts-browser-unity-plugin/tree/master/src/Vts/Documentation#vts-cache

But in Unity i don't have access to the variable cachePath or to the mapOptions.
https://github.com/melowntech/vts-browser-cpp/blob/24668af213676db79913b8c595c1b418360f3a6b/browser/src/vts-libbrowser/include/vts-browser/mapOptions.hpp#L53

I need to building the plugin from source code?

**Comment by malytomas** [comment]
The `Vts Map` script has `Create Config` property, which is json-encoded https://github.com/melowntech/vts-browser-cpp/blob/370199da70c8ac9ebf431154b2ce3f78881c9d98/browser/src/vts-libbrowser/include/vts-browser/mapOptions.hpp#L39

Use `{ "cachePath":"the-path" }` for example

**Comment by rafaP** [comment]
Thanks for the fast replay.

I used that property, with { "cachePath":"C:\temp"} but it didn't made a change.

**Comment by malytomas** [comment]
You are right. There was a bug: https://github.com/melowntech/vts-browser-cpp/issues/17
It is fixed now, but there was no public release since then.
I  recommend you to build the plugin until next release.

Also the path should be `{ "cachePath":"C://temp" }` (using forward slashes)

**Comment by rafaP** [comment]
Can you do a build of the plugin?
I'm not familiar with Cmake and builds

Thanks.

**Comment by rafaP** [comment]
I get this error when i try to build the plugin:

-- @@@ including vts browser
CMake Error at externals/browser/externals/browser/browser/CMakeLists.txt:10 (include):
  include could not find load file:

    buildsys/cmake/buildsys.cmake


CMake Error at externals/browser/externals/browser/browser/CMakeLists.txt:11 (enable_hidden_visibility):
  Unknown CMake command "enable_hidden_visibility".

**Comment by malytomas** [comment]
> -- @@@ including vts browser
> CMake Error at externals/browser/externals/browser/browser/CMakeLists.txt:10 (include):
> include could not find load file:
> 
> ```
> buildsys/cmake/buildsys.cmake
> ```

These kinds of issues are usually caused by not cloning the repository recursively or when filesystem symlinks are not enabled.

To clone all git submodules do `git submodule update --init --recursive`.

To make symlinks work, you may need to enable developer mode in windows settings, *and* enable them during git installation.

**Comment by rafaP** [comment]
Still can't build the plugin

**Comment by rafaP** [comment]
After re-installing git it worked. thanks
