### ISSUE TITLE
Latest commit not working

### ISSUE THREAD

**Issue by a180285** [melowntech/vts-browser-unity-plugin#28]
I was using the latest master to build at our own Windows 10 PC.

After building the dll, and put dlls to unity. I still get this error.

I was using vts source code with my built dlls.

![image](https://user-images.githubusercontent.com/8207732/129830720-d1908d67-ae46-47b1-b7e3-91670385da65.png)

Get following error.

Assets\Vts\Scripts\BrowserUtil\VtsResources.cs(38,49): error CS0234: The type or namespace name 'Texture' does not exist in the namespace 'vts' (are you missing an assembly reference?)

**Comment by a180285** [comment]
I just tried the previous commit, it works.

commit details.
fix triangles flashing with atmosphere
@malytomas
malytomas committed on Jan 12

**Comment by malytomas** [comment]
Hi Huang Wei,
in the picture, you have the dll excluded from both standalone and editor platforms.
Please check that and let me know if the problem persists.

**Comment by a180285** [comment]
Thanks, that issue resolve. The Unity Editor UI is very tricky any way.
