### ISSUE TITLE
VTS third person

### ISSUE THREAD

**Issue by Zeliktric** [melowntech/vts-browser-unity-plugin#29]
Hello, I have a question:

How would I use the Unity asset for like a flight simulator?
Secondly, I've heard that there is no build for Android, so does that mean if I use the Unity asset, it won't work on Android?

Thank you.

**Comment by malytomas** [comment]
Hi,

take a look at this project: https://github.com/melowntech/VtsJetFighter
It is old and unlikely to work with recent versions of Unity. But the usage of the VTS components should be the same.

The VTS plugin currently does not work on android. This is tracked in https://github.com/melowntech/vts-browser-unity-plugin/issues/3

Let me know if you have any more specific questions.
tm
