### ISSUE TITLE
How do I change coordinates of the map?

### ISSUE THREAD

**Issue by adgsenpai** [melowntech/vts-browser-unity-plugin#31]
Please provide me with information or documentation on how to change the coordinates of the map?

**Comment by malytomas** [comment]
Use script `Vts Map Make Local`.
It will use the position that is stored in mapConfig.json.
Or you can uncheck `Default Position` and provide your own position.

**Comment by adgsenpai** [comment]
Thanks a lot, will play around.

Best Regards
Ashlin Darius Govindasamy
