### ISSUE TITLE
Compiling for x86 ?

### ISSUE THREAD

**Issue by davvdg** [melowntech/vts-browser-unity-plugin#7]
Hi ! I'd like to use the unity plugin and cpp browser with the Hololens V1. unfortunatly, it's only supporting x86, not 64. For my knowledge, why is it not allowed to compile both libs in 32bits mode ? could it be possible ?

David

**Comment by malytomas** [comment]
Hi David,
the biggest problems are alignment issues for math structures provided by eigen.
One may disable simd instructions, which leads to performance degradation. You may try that, I can actually assure you that someone else has already tried that and it is possible.

It would be even better to actually ensure correct alignment in the code. I would gladly accept a PR if you manage to make it work without disabling simd.

Let me know if you find any other problems.
