### ISSUE TITLE
Missing the Browser folder

### ISSUE THREAD

**Issue by 980591032** [melowntech/vts-browser-unity-plugin#9]
![image](https://user-images.githubusercontent.com/44353382/64500014-1baeca00-d2ee-11e9-8793-cdf441ca11ef.png)

Browser folder in VTS plug-in. There is no Browser folder in this project.

**Comment by malytomas** [comment]
The Browser folder is symlink to a folder inside another repository. You need to clone this repository with the --recursive switch.

```bash
git clone --recursive https://github.com/melowntech/vts-browser-unity-plugin.git
cd vts-browser-unity-plugin
mkdir build
cd build
cmake -G"Visual Studio 15 2017 Win64" ..
cmake --build . --config relwithdebinfo
```

**Comment by 980591032** [comment]
Thank you very much for your help. I succeeded. Thank you again.




------------------ 原始邮件 ------------------
发件人: "Tomáš Malý"<notifications@github.com>;
发送时间: 2019年9月9日(星期一) 下午4:53
收件人: "melowntech/vts-browser-unity-plugin"<vts-browser-unity-plugin@noreply.github.com>;
抄送: "自由如风"<980591032@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [melowntech/vts-browser-unity-plugin] Loss of Unity script forproject import (#9)




The Browser folder is symlink to a folder inside another repository. You need to clone this repository with the --recursive switch.
 git clone --recursive https://github.com/melowntech/vts-browser-unity-plugin.git cd vts-browser-unity-plugin mkdir build cd build cmake -G"Visual Studio 15 2017 Win64" .. cmake --build . --config relwithdebinfo

**Comment by malytomas** [comment]
Great. I hope you will like the VTS. I am closing the relevant issues now.
